
[build.environment]
  NPM_VERSION = "6.14.8"
  NODE_VERSION = "12.16.3"

[build]
  publish = "doc/_build/html"
  command = "npm run build"

[context.production]
  publish = "doc/_build/html"
  command = "npm run build"

[context.deploy-preview]
  publish = "doc/_build/html"
  command = "npm run build"

[[redirects]]
  from = "/"
  to = "/docs/rackspace-federation/"
  status = 301
  force = false

[[redirects]]
  from = "/*"
  to = "/docs/rackspace-federation/:splat"
  status = 301
  force = false