
[build.environment]
  NPM_VERSION = "6.14.8"
  NODE_VERSION = "12.16.3"

[build]
  publish = "doc/_build/html"
  command = "cd doc && make clean html && cd .."

[context.production]
  publish = "doc/_build/html"
  command = "cd doc && make clean html && cd .."

[context.deploy-preview]
  publish = "doc/_build/html"
  command = "cd doc && make clean html && cd .."

[[redirects]]
  from = "/*"
  to = "/docs/rackspace-federation/:splat"
  status = 301
  force = false